spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clean-spring
    password: 1234
    username: victor
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081